
services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: felipesouza
      ME_CONFIG_BASICAUTH_PASSWORD: mongodbexpress
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_started
      api:
        condition: service_started
    networks:
      - api-network

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: 'pets_ranked_api_production'
    ports:
      - "27017:27017"
    volumes:
      - /f/Documentos/Projetos/Development/Github/PetsRankedAPI/MongoDB:/data/db
    networks:
      - api-network

  api:
    build: .
    working_dir: /app
    container_name: api
    ports:
      - '3000:3000'
    command: bash -c "rm -f tmp/pids/server.pid || true && bin/setup && bundle exec rails s -b 0.0.0.0"
    environment:
      MONGODB_URL: mongodb://mongo:27017/
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - .:/app
    depends_on:
      mongo:
        condition: service_started
    links:
      - mongo
    networks:
      - api-network

networks: 
    api-network:
      driver: bridge