
services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: adminexpress
      ME_CONFIG_BASICAUTH_PASSWORD: adminexpress
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_started
      api:
        condition: service_started
    networks:
      - api-network

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: 'pets_ranked_api_production'
    ports:
      - "27017:27017"
    volumes:
      - ./MongoDB:/data/db
    networks:
      - api-network

  keycloak:
    image: keycloak/keycloak
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: ["start-dev","--http-port=9000"]
    ports:
      - '9000:9000'
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      interval: 10s
      timeout: 10s
      retries: 6
    networks:
      - api-network
  
  
  api:
    build: .
    working_dir: /app
    container_name: api
    ports:
      - '3000:3000'
    command: bash -c "rm -f tmp/pids/server.pid || true && bin/setup && bundle exec rails s -b 0.0.0.0"
    environment:
      MONGODB_URL: mongodb://mongo:27017/
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - .:/app
    depends_on:
      mongo:
        condition: service_started
      keycloak:
        condition: service_healthy
    links:
      - mongo
    networks:
      - api-network

networks: 
    api-network:
      driver: bridge